// internal/git/git.go
package git

import (
	"fmt"
	"os/exec"
	"regexp"
	"strings"
)

// Git provides git operations for a repository
type Git struct {
	repoPath string
}

// New creates a Git instance for the given repository path
func New(repoPath string) *Git {
	return &Git{repoPath: repoPath}
}

// BranchName creates a sanitized branch name from task ID and title
func BranchName(taskID, title string) string {
	// Lowercase and replace spaces with hyphens
	slug := strings.ToLower(title)
	slug = strings.ReplaceAll(slug, " ", "-")

	// Remove non-alphanumeric characters except hyphens
	reg := regexp.MustCompile(`[^a-z0-9-]`)
	slug = reg.ReplaceAllString(slug, "")

	// Remove consecutive hyphens
	reg = regexp.MustCompile(`-+`)
	slug = reg.ReplaceAllString(slug, "-")

	// Trim hyphens from ends
	slug = strings.Trim(slug, "-")

	// Truncate to reasonable length (30 chars for slug)
	if len(slug) > 30 {
		slug = slug[:30]
		// Don't end on a hyphen
		slug = strings.TrimRight(slug, "-")
	}

	return fmt.Sprintf("task/%s-%s", taskID, slug)
}

// run executes a git command and returns output
func (g *Git) run(args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = g.repoPath

	output, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("git %s: %w: %s", strings.Join(args, " "), err, output)
	}
	return strings.TrimSpace(string(output)), nil
}

// CurrentBranch returns the current branch name
func (g *Git) CurrentBranch() (string, error) {
	return g.run("rev-parse", "--abbrev-ref", "HEAD")
}

// CreateBranch creates and checks out a new branch
func (g *Git) CreateBranch(name string) error {
	_, err := g.run("checkout", "-b", name)
	return err
}

// SwitchBranch switches to an existing branch
func (g *Git) SwitchBranch(name string) error {
	_, err := g.run("checkout", name)
	return err
}

// HasUncommittedChanges returns true if there are uncommitted changes
func (g *Git) HasUncommittedChanges() (bool, error) {
	output, err := g.run("status", "--porcelain")
	if err != nil {
		return false, err
	}
	return output != "", nil
}

// Add stages files for commit
func (g *Git) Add(paths ...string) error {
	args := append([]string{"add"}, paths...)
	_, err := g.run(args...)
	return err
}

// Commit creates a commit with the given message
func (g *Git) Commit(message string) error {
	_, err := g.run("commit", "-m", message)
	return err
}

// Push pushes the current branch to origin
func (g *Git) Push() error {
	branch, err := g.CurrentBranch()
	if err != nil {
		return err
	}
	_, err = g.run("push", "-u", "origin", branch)
	return err
}

// GetDiff returns the diff for staged changes
func (g *Git) GetDiff() (string, error) {
	return g.run("diff", "--staged")
}

// GetLog returns recent commit messages
func (g *Git) GetLog(count int) (string, error) {
	return g.run("log", fmt.Sprintf("-%d", count), "--oneline")
}

// PRInfo contains information for creating a pull request
type PRInfo struct {
	Title   string
	Summary string
	TaskIDs []string
	Agents  []string
	Metrics PRMetrics
}

// PRMetrics tracks work done for a PR
type PRMetrics struct {
	TokensUsed  int64
	TimeMinutes int
}

// GenerateBody creates the PR body markdown
func (p *PRInfo) GenerateBody() string {
	var sb strings.Builder

	sb.WriteString("## Summary\n")
	sb.WriteString(p.Summary)
	sb.WriteString("\n\n")

	sb.WriteString("## Tasks Completed\n")
	for _, id := range p.TaskIDs {
		sb.WriteString(fmt.Sprintf("- [x] %s\n", id))
	}
	sb.WriteString("\n")

	sb.WriteString("## Agents Involved\n")
	for _, agent := range p.Agents {
		sb.WriteString(fmt.Sprintf("- %s\n", agent))
	}
	sb.WriteString("\n")

	sb.WriteString("## Metrics\n")
	sb.WriteString(fmt.Sprintf("- Tokens used: %s\n", formatNumber(p.Metrics.TokensUsed)))
	sb.WriteString(fmt.Sprintf("- Time: %dm\n", p.Metrics.TimeMinutes))
	sb.WriteString("\n")

	sb.WriteString("---\n")
	sb.WriteString("Generated by CLIAIMONITOR team-coop\n")

	return sb.String()
}

// formatNumber adds thousand separators
func formatNumber(n int64) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}

	var result strings.Builder
	for i, c := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			result.WriteRune(',')
		}
		result.WriteRune(c)
	}
	return result.String()
}

// CreatePR creates a pull request using gh CLI
func (g *Git) CreatePR(pr PRInfo) (string, error) {
	body := pr.GenerateBody()

	output, err := g.run("gh", "pr", "create",
		"--title", pr.Title,
		"--body", body)
	if err != nil {
		return "", fmt.Errorf("failed to create PR: %w", err)
	}

	// Output should be the PR URL
	return output, nil
}

// MergePR merges a pull request using squash
func (g *Git) MergePR(prURL string) error {
	// Extract PR number from URL
	parts := strings.Split(prURL, "/")
	prNum := parts[len(parts)-1]

	_, err := g.run("gh", "pr", "merge", prNum, "--squash", "--delete-branch")
	return err
}
